<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        DB::table('tbl_users')->insert([
            [
                'username' => 'user1',
                'email' => 'user1@example.com',
                'password' => md5('password1'),
                'activation_token' => null,
                'isActive' => 'y',
                'fullName' => 'Nguyen Van A',
                'phoneNumber' => '0123456789',
                'address' => '123 Đường A, Quận 1, TP.HCM',
                'ipAddress' => '127.0.0.1',
                'status' => null,
                'createdDate' => now(),
                'updatedDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'user2',
                'email' => 'user2@example.com',
                'password' => md5('password2'),
                'activation_token' => null,
                'isActive' => 'y',
                'fullName' => 'Tran Thi B',
                'phoneNumber' => '0987654321',
                'address' => '456 Đường B, Quận 2, TP.HCM',
                'ipAddress' => '127.0.0.2',
                'status' => null,
                'createdDate' => now(),
                'updatedDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'user3',
                'email' => 'user3@example.com',
                'password' => md5('password3'),
                'activation_token' => null,
                'isActive' => 'y',
                'fullName' => 'Le Thi C',
                'phoneNumber' => '0911222333',
                'address' => '789 Đường C, Quận 3, TP.HCM',
                'ipAddress' => '127.0.0.3',
                'status' => null,
                'createdDate' => now(),
                'updatedDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('tbl_admin')->insert([
            [
                'username' => 'admin1',
                'password' => md5('adminpassword1'),
                'email' => 'admin1@example.com',
                'fullName' => 'Admin One',
                'address' => '123 Admin Street, TP.HCM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('tbl_tours')->insert([
            [
                'title' => 'Tour Hà Nội - Hạ Long',
                'description' => 'Khám phá vịnh Hạ Long tuyệt đẹp.',
                'priceAdult' => 2500000,
                'priceChild' => 1800000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Hạ Long',
                'quantity' => 30,
                'domain' => 'b',
                'startDate' => '2025-07-01',
                'endDate' => '2025-07-03',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Sapa - Fansipan',
                'description' => 'Chinh phục nóc nhà Đông Dương.',
                'priceAdult' => 3200000,
                'priceChild' => 2200000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Sapa',
                'quantity' => 25,
                'domain' => 'b',
                'startDate' => '2025-07-10',
                'endDate' => '2025-07-13',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Đà Nẵng - Hội An',
                'description' => 'Khám phá phố cổ Hội An và biển Đà Nẵng.',
                'priceAdult' => 2800000,
                'priceChild' => 2000000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Đà Nẵng',
                'quantity' => 40,
                'domain' => 't',
                'startDate' => '2025-08-01',
                'endDate' => '2025-08-03',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Huế - Quảng Bình',
                'description' => 'Tham quan cố đô Huế và động Phong Nha.',
                'priceAdult' => 2700000,
                'priceChild' => 1900000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Huế',
                'quantity' => 35,
                'domain' => 't',
                'startDate' => '2025-08-10',
                'endDate' => '2025-08-12',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Nha Trang - Đà Lạt',
                'description' => 'Biển xanh Nha Trang và cao nguyên Đà Lạt.',
                'priceAdult' => 3500000,
                'priceChild' => 2500000,
                'time' => '5 ngày 4 đêm',
                'destination' => 'Nha Trang',
                'quantity' => 20,
                'domain' => 'n',
                'startDate' => '2025-09-01',
                'endDate' => '2025-09-05',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Phú Quốc',
                'description' => 'Thiên đường biển đảo Phú Quốc.',
                'priceAdult' => 4000000,
                'priceChild' => 3000000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Phú Quốc',
                'quantity' => 30,
                'domain' => 'n',
                'startDate' => '2025-09-15',
                'endDate' => '2025-09-18',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Cần Thơ - Sóc Trăng',
                'description' => 'Khám phá miền Tây sông nước.',
                'priceAdult' => 2200000,
                'priceChild' => 1500000,
                'time' => '2 ngày 1 đêm',
                'destination' => 'Cần Thơ',
                'quantity' => 50,
                'domain' => 'n',
                'startDate' => '2025-10-01',
                'endDate' => '2025-10-02',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Hà Giang',
                'description' => 'Chinh phục cao nguyên đá Đồng Văn.',
                'priceAdult' => 3300000,
                'priceChild' => 2300000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Hà Giang',
                'quantity' => 15,
                'domain' => 'b',
                'startDate' => '2025-10-15',
                'endDate' => '2025-10-18',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Buôn Ma Thuột',
                'description' => 'Khám phá thủ phủ cà phê Tây Nguyên.',
                'priceAdult' => 2600000,
                'priceChild' => 1800000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Buôn Ma Thuột',
                'quantity' => 18,
                'domain' => 'n',
                'startDate' => '2025-11-01',
                'endDate' => '2025-11-03',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Côn Đảo',
                'description' => 'Khám phá di tích lịch sử và biển đảo Côn Đảo.',
                'priceAdult' => 4200000,
                'priceChild' => 3200000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Côn Đảo',
                'quantity' => 12,
                'domain' => 'n',
                'startDate' => '2025-11-15',
                'endDate' => '2025-11-18',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('tbl_images')->insert([
            [
                'tourId' => 1,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Vịnh Hạ Long nhìn từ trên cao.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 1,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Vịnh Hạ Long nhìn từ trên cao.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 1,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Vịnh Hạ Long nhìn từ trên cao.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 1,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Vịnh Hạ Long nhìn từ trên cao.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 1,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Vịnh Hạ Long nhìn từ trên cao.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 2,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Đỉnh Fansipan hùng vĩ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 2,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Đỉnh Fansipan hùng vĩ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 2,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Đỉnh Fansipan hùng vĩ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 2,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Đỉnh Fansipan hùng vĩ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 2,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Đỉnh Fansipan hùng vĩ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 3,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Phố cổ Hội An lung linh đèn lồng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 3,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Phố cổ Hội An lung linh đèn lồng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 3,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Phố cổ Hội An lung linh đèn lồng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 3,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Phố cổ Hội An lung linh đèn lồng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 3,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Phố cổ Hội An lung linh đèn lồng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 4,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cố đô Huế cổ kính.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 4,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cố đô Huế cổ kính.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 4,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cố đô Huế cổ kính.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 4,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cố đô Huế cổ kính.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 4,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cố đô Huế cổ kính.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 5,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 5,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 5,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 5,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 5,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 6,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Bãi biển Phú Quốc tuyệt đẹp.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 6,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Bãi biển Phú Quốc tuyệt đẹp.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 6,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Bãi biển Phú Quốc tuyệt đẹp.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 6,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Bãi biển Phú Quốc tuyệt đẹp.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 6,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Bãi biển Phú Quốc tuyệt đẹp.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
