<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        DB::table('tbl_users')->insert([
            [
                'username' => 'user1',
                'email' => 'user1@example.com',
                'password' => md5('password1'),
                'activation_token' => null,
                'isActive' => 'y',
                'fullName' => 'Nguyen Van A',
                'phoneNumber' => '0123456789',
                'address' => '123 Đường A, Quận 1, TP.HCM',
                'ipAddress' => '127.0.0.1',
                'status' => null,
                'createdDate' => now(),
                'updatedDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'user2',
                'email' => 'user2@example.com',
                'password' => md5('password2'),
                'activation_token' => null,
                'isActive' => 'y',
                'fullName' => 'Tran Thi B',
                'phoneNumber' => '0987654321',
                'address' => '456 Đường B, Quận 2, TP.HCM',
                'ipAddress' => '127.0.0.2',
                'status' => null,
                'createdDate' => now(),
                'updatedDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => 'user3',
                'email' => 'user3@example.com',
                'password' => md5('password3'),
                'activation_token' => null,
                'isActive' => 'y',
                'fullName' => 'Le Thi C',
                'phoneNumber' => '0911222333',
                'address' => '789 Đường C, Quận 3, TP.HCM',
                'ipAddress' => '127.0.0.3',
                'status' => null,
                'createdDate' => now(),
                'updatedDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('tbl_admin')->insert([
            [
                'username' => 'admin1',
                'password' => md5('adminpassword1'),
                'email' => 'admin1@example.com',
                'fullName' => 'Admin One',
                'address' => '123 Admin Street, TP.HCM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('tbl_tours')->insert([
            [
                'title' => 'Tour Hà Nội - Hạ Long',
                'description' => 'Khám phá vịnh Hạ Long tuyệt đẹp.',
                'priceAdult' => 2500000,
                'priceChild' => 1800000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Hạ Long',
                'quantity' => 30,
                'domain' => 'b',
                'startDate' => '2025-07-01',
                'endDate' => '2025-07-03',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Sapa - Fansipan',
                'description' => 'Chinh phục nóc nhà Đông Dương.',
                'priceAdult' => 3200000,
                'priceChild' => 2200000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Sapa',
                'quantity' => 25,
                'domain' => 'b',
                'startDate' => '2025-07-10',
                'endDate' => '2025-07-13',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Đà Nẵng - Hội An',
                'description' => 'Khám phá phố cổ Hội An và biển Đà Nẵng.',
                'priceAdult' => 2800000,
                'priceChild' => 2000000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Đà Nẵng',
                'quantity' => 40,
                'domain' => 't',
                'startDate' => '2025-08-01',
                'endDate' => '2025-08-03',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Huế - Quảng Bình',
                'description' => 'Tham quan cố đô Huế và động Phong Nha.',
                'priceAdult' => 2700000,
                'priceChild' => 1900000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Huế',
                'quantity' => 35,
                'domain' => 't',
                'startDate' => '2025-08-10',
                'endDate' => '2025-08-12',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Nha Trang - Đà Lạt',
                'description' => 'Biển xanh Nha Trang và cao nguyên Đà Lạt.',
                'priceAdult' => 3500000,
                'priceChild' => 2500000,
                'time' => '5 ngày 4 đêm',
                'destination' => 'Nha Trang',
                'quantity' => 20,
                'domain' => 'n',
                'startDate' => '2025-09-01',
                'endDate' => '2025-09-05',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Phú Quốc',
                'description' => 'Thiên đường biển đảo Phú Quốc.',
                'priceAdult' => 4000000,
                'priceChild' => 3000000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Phú Quốc',
                'quantity' => 30,
                'domain' => 'n',
                'startDate' => '2025-09-15',
                'endDate' => '2025-09-18',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Cần Thơ - Sóc Trăng',
                'description' => 'Khám phá miền Tây sông nước.',
                'priceAdult' => 2200000,
                'priceChild' => 1500000,
                'time' => '2 ngày 1 đêm',
                'destination' => 'Cần Thơ',
                'quantity' => 50,
                'domain' => 'n',
                'startDate' => '2025-10-01',
                'endDate' => '2025-10-02',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Hà Giang',
                'description' => 'Chinh phục cao nguyên đá Đồng Văn.',
                'priceAdult' => 3300000,
                'priceChild' => 2300000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Hà Giang',
                'quantity' => 15,
                'domain' => 'b',
                'startDate' => '2025-10-15',
                'endDate' => '2025-10-18',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Buôn Ma Thuột',
                'description' => 'Khám phá thủ phủ cà phê Tây Nguyên.',
                'priceAdult' => 2600000,
                'priceChild' => 1800000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Buôn Ma Thuột',
                'quantity' => 18,
                'domain' => 'n',
                'startDate' => '2025-11-01',
                'endDate' => '2025-11-03',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Côn Đảo',
                'description' => 'Khám phá di tích lịch sử và biển đảo Côn Đảo.',
                'priceAdult' => 4200000,
                'priceChild' => 3200000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Côn Đảo',
                'quantity' => 12,
                'domain' => 'n',
                'startDate' => '2025-11-15',
                'endDate' => '2025-11-18',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Đà Nẵng - Bà Nà Hills',
                'description' => 'Khám phá Bà Nà Hills và cầu Vàng nổi tiếng.',
                'priceAdult' => 2900000,
                'priceChild' => 2100000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Đà Nẵng',
                'quantity' => 35,
                'domain' => 't',
                'startDate' => '2025-08-15',
                'endDate' => '2025-08-17',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Hà Nội - Ninh Bình',
                'description' => 'Tham quan Tràng An, Bái Đính, di sản thế giới.',
                'priceAdult' => 2400000,
                'priceChild' => 1700000,
                'time' => '2 ngày 1 đêm',
                'destination' => 'Hà Nội',
                'quantity' => 28,
                'domain' => 'b',
                'startDate' => '2025-07-20',
                'endDate' => '2025-07-21',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Sapa - Nhà thờ đá',
                'description' => 'Khám phá nhà thờ đá cổ Sapa và bản Cát Cát.',
                'priceAdult' => 2700000,
                'priceChild' => 1900000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Sapa',
                'quantity' => 22,
                'domain' => 'b',
                'startDate' => '2025-07-25',
                'endDate' => '2025-07-27',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Nha Trang - Hòn Tre',
                'description' => 'Tham quan đảo Hòn Tre và Vinpearl Land.',
                'priceAdult' => 3600000,
                'priceChild' => 2600000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Nha Trang',
                'quantity' => 25,
                'domain' => 'n',
                'startDate' => '2025-09-10',
                'endDate' => '2025-09-12',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Phú Quốc - Bãi Sao',
                'description' => 'Tận hưởng biển xanh và cát trắng Bãi Sao.',
                'priceAdult' => 4100000,
                'priceChild' => 3100000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Phú Quốc',
                'quantity' => 20,
                'domain' => 'n',
                'startDate' => '2025-09-20',
                'endDate' => '2025-09-23',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Cao Bằng - Thác Bản Giốc',
                'description' => 'Khám phá thác Bản Giốc hùng vĩ và động Ngườm Ngao.',
                'priceAdult' => 3200000,
                'priceChild' => 2200000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Cao Bằng',
                'quantity' => 20,
                'domain' => 'b',
                'startDate' => '2025-10-20',
                'endDate' => '2025-10-22',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Cà Mau - Mũi Cà Mau',
                'description' => 'Chinh phục cực Nam Tổ quốc, khám phá rừng ngập mặn.',
                'priceAdult' => 3500000,
                'priceChild' => 2500000,
                'time' => '4 ngày 3 đêm',
                'destination' => 'Cà Mau',
                'quantity' => 18,
                'domain' => 'n',
                'startDate' => '2025-11-10',
                'endDate' => '2025-11-13',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour An Giang - Rừng Tràm Trà Sư',
                'description' => 'Khám phá rừng tràm Trà Sư và làng cá bè Châu Đốc.',
                'priceAdult' => 2700000,
                'priceChild' => 1800000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'An Giang',
                'quantity' => 22,
                'domain' => 'n',
                'startDate' => '2025-09-25',
                'endDate' => '2025-09-27',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Bình Định - Eo Gió',
                'description' => 'Check-in Eo Gió, Kỳ Co và Tháp Đôi Quy Nhơn.',
                'priceAdult' => 3300000,
                'priceChild' => 2300000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Bình Định',
                'quantity' => 24,
                'domain' => 't',
                'startDate' => '2025-08-20',
                'endDate' => '2025-08-22',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tour Phú Yên - Gành Đá Đĩa',
                'description' => 'Khám phá Gành Đá Đĩa và biển Phú Yên.',
                'priceAdult' => 3100000,
                'priceChild' => 2100000,
                'time' => '3 ngày 2 đêm',
                'destination' => 'Phú Yên',
                'quantity' => 20,
                'domain' => 'n',
                'startDate' => '2025-09-05',
                'endDate' => '2025-09-07',
                'availability' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('tbl_images')->insert([
            // Tour 1: Hà Nội - Hạ Long
            [
                'tourId' => 1,
                'imageUrl' => 'vinh-ha-long-quang-ninh_1735834627.jpg',
                'description' => 'Vịnh Hạ Long nhìn từ trên cao.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 1,
                'imageUrl' => 'vinh-ha-long_1732896698.png',
                'description' => 'Vẻ đẹp kỳ vĩ của vịnh Hạ Long.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 1,
                'imageUrl' => 'cau-the-huc_1735834628.jpg',
                'description' => 'Cầu Thê Húc Hà Nội.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 1,
                'imageUrl' => 'ho-hoan-kiem_1735834629.jpg',
                'description' => 'Hồ Hoàn Kiếm Hà Nội.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 1,
                'imageUrl' => 'khu-du-lich-trang-an-ninh-binh_1732896697.jpg',
                'description' => 'Tràng An Ninh Bình.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 2: Sapa - Fansipan
            [
                'tourId' => 2,
                'imageUrl' => 'dinh-fansipan-sapa_1732898213.png',
                'description' => 'Đỉnh Fansipan hùng vĩ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 2,
                'imageUrl' => 'bich-van-thien-tu-sapa_1732898210.png',
                'description' => 'Bích Vân Thiên Tự Sapa.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 2,
                'imageUrl' => 'nha-tho-da-sapa_1732898214.png',
                'description' => 'Nhà thờ đá Sapa.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 2,
                'imageUrl' => 'chinh-phuc-deo-ma-pi-leng_1732897625.jpeg',
                'description' => 'Đèo Mã Pí Lèng Sapa.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 2,
                'imageUrl' => 'bich-van-thien-tu-sapa_1732898210.png',
                'description' => 'Khung cảnh Sapa tuyệt đẹp.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 3: Đà Nẵng - Hội An
            [
                'tourId' => 3,
                'imageUrl' => 'cau-vang-da-nang_1732896303.png',
                'description' => 'Cầu Vàng Đà Nẵng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 3,
                'imageUrl' => 'ba-na-hill-da-nang-1_1732896298.png',
                'description' => 'Bà Nà Hills Đà Nẵng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 3,
                'imageUrl' => 'pho-co-hoi-an_1732895857.jpg',
                'description' => 'Phố cổ Hội An lung linh đèn lồng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 3,
                'imageUrl' => 'ben-trong-ba-na-hills-da-nang_1732896301.png',
                'description' => 'Khám phá bên trong Bà Nà Hills.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 3,
                'imageUrl' => 'khung-canh-da-nang-tu-tren-cao_1732895859.png',
                'description' => 'Toàn cảnh Đà Nẵng từ trên cao.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 4: Huế - Quảng Bình
            [
                'tourId' => 4,
                'imageUrl' => 'kinh-thanh-hue_1732897888.png',
                'description' => 'Kinh thành Huế cổ kính.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 4,
                'imageUrl' => 'cau-truong-tien-hue_1732897879.png',
                'description' => 'Cầu Trường Tiền Huế.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 4,
                'imageUrl' => 'kinh-thanh-hue-min_1732896295.png',
                'description' => 'Kinh thành Huế nhìn từ trên cao.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 4,
                'imageUrl' => 'cau-truong-tien-hue_1732897879.png',
                'description' => 'Cầu Trường Tiền về đêm.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 4,
                'imageUrl' => 'kinh-thanh-hue_1732897888.png',
                'description' => 'Cố đô Huế cổ kính.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 5: Nha Trang - Đà Lạt
            [
                'tourId' => 5,
                'imageUrl' => 'hon-tre-nha-trang_1734022644.jpg',
                'description' => 'Đảo Hòn Tre Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 5,
                'imageUrl' => 'vinpearl-nha-trang_1734022646.jpg',
                'description' => 'Vinpearl Land Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 5,
                'imageUrl' => 'vien-hai-duong-hoc-nha-trang_1734022645.jpg',
                'description' => 'Viện Hải dương học Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 5,
                'imageUrl' => 'vinh-san-ho-nha-trang_1734022645.jpg',
                'description' => 'Vịnh San Hô Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 5,
                'imageUrl' => 'da-lat-view_1734022793.jpg',
                'description' => 'Cao nguyên Đà Lạt.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 6: Phú Quốc
            [
                'tourId' => 6,
                'imageUrl' => 'bai-sao-phu-quoc_1732895312.jpg',
                'description' => 'Bãi Sao Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 6,
                'imageUrl' => 'grand-world-phu-quoc_1732895310.jpg',
                'description' => 'Grand World Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 6,
                'imageUrl' => 'hon-gam-ghi-phu-quoc_1732895313.jpg',
                'description' => 'Hòn Gầm Ghì Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 6,
                'imageUrl' => 'hon-mong-tay-phu-quoc_1732895311.jpg',
                'description' => 'Hòn Móng Tay Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 6,
                'imageUrl' => 'thi-tran-hoang-hon-phu-quoc_1732895312.jpg',
                'description' => 'Thị trấn Hoàng Hôn Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 7: Cần Thơ - Sóc Trăng
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 7,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Chợ nổi Cần Thơ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 8: Hà Giang
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 8,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Cao nguyên đá Đồng Văn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 9: Buôn Ma Thuột
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 9,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Thủ phủ cà phê Buôn Ma Thuột.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 10: Côn Đảo
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 10,
                'imageUrl' => '5-du-khach-co-the-chiem-nguong-tron-ven-canh-tay-bac-o-dinh-fansipan_1732896696.jpg',
                'description' => 'Biển xanh và di tích Côn Đảo.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 11,
                'imageUrl' => 'ba-na-hill-da-nang-1_1732896298.png',
                'description' => 'Bà Nà Hills Đà Nẵng tuyệt đẹp.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 11,
                'imageUrl' => 'cau-vang-da-nang_1732896303.png',
                'description' => 'Cầu Vàng nổi tiếng Đà Nẵng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 11,
                'imageUrl' => 'ben-trong-ba-na-hills-da-nang_1732896301.png',
                'description' => 'Khám phá bên trong Bà Nà Hills.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 11,
                'imageUrl' => 'cong-vien-fantasy-park_1732895849.jpg',
                'description' => 'Công viên Fantasy Park.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 11,
                'imageUrl' => 'khung-canh-da-nang-tu-tren-cao_1732895859.png',
                'description' => 'Toàn cảnh Đà Nẵng từ trên cao.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 12 - Hà Nội - Ninh Bình
            [
                'tourId' => 12,
                'imageUrl' => 'cau-the-huc_1735834628.jpg',
                'description' => 'Cầu Thê Húc Hà Nội.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 12,
                'imageUrl' => 'khu-du-lich-trang-an-ninh-binh_1732896697.jpg',
                'description' => 'Tràng An Ninh Bình.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 12,
                'imageUrl' => 'chua-bai-dinh_1732896696.jpg',
                'description' => 'Chùa Bái Đính Ninh Bình.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 12,
                'imageUrl' => 'ho-hoan-kiem_1732896697.jpg',
                'description' => 'Hồ Hoàn Kiếm Hà Nội.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 12,
                'imageUrl' => 'lang-chu-tich-ho-chi-minh_1732898212.png',
                'description' => 'Lăng Chủ tịch Hồ Chí Minh.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 13 - Sapa - Nhà thờ đá
            [
                'tourId' => 13,
                'imageUrl' => 'nha-tho-da-sapa_1732898214.png',
                'description' => 'Nhà thờ đá Sapa.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 13,
                'imageUrl' => 'bich-van-thien-tu-sapa_1732898210.png',
                'description' => 'Bích Vân Thiên Tự Sapa.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 13,
                'imageUrl' => 'dinh-fansipan-sapa_1732898213.png',
                'description' => 'Đỉnh Fansipan Sapa.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 13,
                'imageUrl' => 'bich-van-thien-tu-sapa_1732898210.png',
                'description' => 'Khung cảnh Sapa tuyệt đẹp.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 13,
                'imageUrl' => 'bich-van-thien-tu-sapa_1732898210.png',
                'description' => 'Sapa mờ sương.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 14 - Nha Trang - Hòn Tre
            [
                'tourId' => 14,
                'imageUrl' => 'hon-tre-nha-trang_1734022644.jpg',
                'description' => 'Đảo Hòn Tre Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 14,
                'imageUrl' => 'vinpearl-nha-trang_1734022646.jpg',
                'description' => 'Vinpearl Land Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 14,
                'imageUrl' => 'vien-hai-duong-hoc-nha-trang_1734022645.jpg',
                'description' => 'Viện Hải dương học Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 14,
                'imageUrl' => 'vinh-san-ho-nha-trang_1734022645.jpg',
                'description' => 'Vịnh San Hô Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 14,
                'imageUrl' => 'bien-my-khe_1732895854.jpg',
                'description' => 'Biển Mỹ Khê Nha Trang.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 15 - Phú Quốc - Bãi Sao
            [
                'tourId' => 15,
                'imageUrl' => 'bai-sao-phu-quoc_1732895312.jpg',
                'description' => 'Bãi Sao Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 15,
                'imageUrl' => 'grand-world-phu-quoc_1732895310.jpg',
                'description' => 'Grand World Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 15,
                'imageUrl' => 'hon-gam-ghi-phu-quoc_1732895313.jpg',
                'description' => 'Hòn Gầm Ghì Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 15,
                'imageUrl' => 'hon-mong-tay-phu-quoc_1732895311.jpg',
                'description' => 'Hòn Móng Tay Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 15,
                'imageUrl' => 'thi-tran-hoang-hon-phu-quoc_1732895312.jpg',
                'description' => 'Thị trấn Hoàng Hôn Phú Quốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 16: Cao Bằng - Thác Bản Giốc
            [
                'tourId' => 16,
                'imageUrl' => 'thac-ban-gioc-cao-bang_1732897627.png',
                'description' => 'Thác Bản Giốc hùng vĩ.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 16,
                'imageUrl' => 'dong-nguom-ngao_1732897626.jpg',
                'description' => 'Động Ngườm Ngao kỳ bí.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 16,
                'imageUrl' => 'cot-co-lung-cu-ha-giang_1732897626.png',
                'description' => 'Cột cờ Lũng Cú.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 16,
                'imageUrl' => 'khu-di-tich-danh-thang-nhi-tam-thanh_1732897625.jpg',
                'description' => 'Danh thắng Tam Thanh.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 16,
                'imageUrl' => 'chinh-phuc-deo-ma-pi-leng_1732897625.jpeg',
                'description' => 'Đèo Mã Pí Lèng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 17: Cà Mau - Mũi Cà Mau
            [
                'tourId' => 17,
                'imageUrl' => 'VQG_MUI_CA_MAU__5__1732933788.jpg',
                'description' => 'Vườn quốc gia Mũi Cà Mau.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 17,
                'imageUrl' => 'VUON_QUOC_GIA_MUI_CA_MAU-BAI_BOI__2__1732933787.jpg',
                'description' => 'Bãi bồi Mũi Cà Mau.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 17,
                'imageUrl' => 'tfd_240925035112_435229_VQG_MUI_CA_MAU__3__1732933787.jpg',
                'description' => 'Khám phá rừng ngập mặn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 17,
                'imageUrl' => 'tfd_240103060657_209766_LANG_CA_BE_CHAU_DOC_1732934361.jpg',
                'description' => 'Làng cá bè Châu Đốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 17,
                'imageUrl' => 'tfd_240103060657_209766_LANG_CA_BE_CHAU_DOC_1732936283.jpg',
                'description' => 'Trải nghiệm miền Tây.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 18: An Giang - Rừng Tràm Trà Sư
            [
                'tourId' => 18,
                'imageUrl' => 'tfd_241016022221_931167_RUNG_TRAM_TRA_SU__2__1732934364.jpg',
                'description' => 'Rừng tràm Trà Sư.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 18,
                'imageUrl' => 'tfd_241016022221_931167_RUNG_TRAM_TRA_SU__2__1732936284.jpg',
                'description' => 'Khám phá rừng tràm.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 18,
                'imageUrl' => 'tfd_240103060657_209766_LANG_CA_BE_CHAU_DOC_1732934361.jpg',
                'description' => 'Làng cá bè Châu Đốc.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 18,
                'imageUrl' => 'tfd_240103060657_209766_LANG_CA_BE_CHAU_DOC_1732936283.jpg',
                'description' => 'Trải nghiệm miền Tây.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 18,
                'imageUrl' => 'tfd_241016022402_471049_CHO_NOI_CAI_RANG__1__1732934237.jpg',
                'description' => 'Chợ nổi Cái Răng.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 19: Bình Định - Eo Gió
            [
                'tourId' => 19,
                'imageUrl' => 'tfd_240925042625_062981_EO_GIO_4_1732937028.jpg',
                'description' => 'Eo Gió Quy Nhơn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 19,
                'imageUrl' => 'tfd_240925042348_413727_Thap_Doi_1732937027.jpg',
                'description' => 'Tháp Đôi Quy Nhơn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 19,
                'imageUrl' => 'tfd_240925041939_234049_Ganh_Da_Dia__1__1732937026.jpg',
                'description' => 'Gành Đá Đĩa Phú Yên.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 19,
                'imageUrl' => 'tfd_240925042243_172671_Quang_Duc_Xua__1__1732937027.jpg',
                'description' => 'Quảng Đức Xưa.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 19,
                'imageUrl' => 'tfd_240625044122_640003_BOBLA__5__1732936524.jpg',
                'description' => 'Bobla Bình Định.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Tour 20: Phú Yên - Gành Đá Đĩa
            [
                'tourId' => 20,
                'imageUrl' => 'tfd_240925041939_234049_Ganh_Da_Dia__1__1732937026.jpg',
                'description' => 'Gành Đá Đĩa Phú Yên.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 20,
                'imageUrl' => 'tfd_240925042243_172671_Quang_Duc_Xua__1__1732937027.jpg',
                'description' => 'Quảng Đức Xưa.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 20,
                'imageUrl' => 'tfd_240925042348_413727_Thap_Doi_1732937027.jpg',
                'description' => 'Tháp Đôi Quy Nhơn.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 20,
                'imageUrl' => 'tfd_240625044122_640003_BOBLA__5__1732936524.jpg',
                'description' => 'Bobla Bình Định.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tourId' => 20,
                'imageUrl' => 'tfd_240925035112_435229_VQG_MUI_CA_MAU__3__1732933787.jpg',
                'description' => 'Vườn quốc gia Mũi Cà Mau.',
                'uploadDate' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}